version: '3'
services:
    db:
        image: postgres:11.2
        volumes:
          - "/usr/local/var/postgres:/var/lib/postgresql/data"
        ports:
          - "5432:5432"
        expose:
          - 5432
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
          - RABBITMQ_DEFAULT_USER=tm
          - RABBITMQ_DEFAULT_PASS=tasky
        ports:
          - "5672:5672"
        expose:
          - 5672
    worker-default:
      image: taskmanager:latest
      entrypoint:
        - celery
        - -A
        - taskmanager.views
        - worker
        - --concurrency=20
        - --loglevel=info
      environment:
        - QUEUE=default
        - CONCURRENT=10
      hostname: default-worker
      volumes:
        - .:/app
      depends_on:
        - rabbit
    worker-1:
      image: taskmanager:latest
      entrypoint:
        - celery
        - -A
        - taskmanager.views
        - worker
        - --concurrency=20
        - --loglevel=info
      environment:
        - QUEUE=worker1
        - CONCURRENT=10
      hostname: worker1
      volumes:
        - .:/app
      depends_on:
        - rabbit
    scheduler:
      image: taskmanager:latest
      entrypoint:
        - task_scheduler
        - development.ini
      hostname: task-scheduler
      depends_on:
        - db
        - rabbit
      volumes:
        - /app
    state-updater:
      image: taskmanager:latest
      entrypoint:
        - state_updater
        - development.ini
      hostname: state-updater
      depends_on:
        - db
        - rabbit
      volumes:
        - /app        
